apiVersion: v1
kind: Secret
# This yaml file is used to create a secret
metadata:
  name: mongo-secret
type: Opaque
# Default for arbitrary key-value pairs
data:
  mongo-user: bW9uZ291c2Vy
  mongo-password: bW9uZ29wYXNzd29yZA==
  # These values must be encrypted using a 3rd party
  # This was done through mac terminal with following commands:
  # :$ echo -n mongouser | base64
  # :$ echo -n mongopassword | base64