# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run | 'on' section states the GitHub events of when this workflow will be triggered
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a job called "build" and "test"
  # Every job will have a 'runs-on' section and a 'steps' section
  build:

    # The type of runner that the job, "build"  will run on 
    runs-on: ubuntu-latest
    
    # Optional section below - indicating the environment
    environment: 
      name: Production

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # The '-' groups chunks of code as a sub-step/action
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
  # By default all jobs run parallely unless we include needs statement then it'll wait for the mentioned job to finish executing        
  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
